services:
  postgres:
    image: postgres:17

    container_name: lyra-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: lyra
      POSTGRES_PASSWORD: lyra123
      POSTGRES_DB: lyra

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
